### PR TITLE
Add H3 and parallelize SSH checks

### PR DESCRIPTION
**Pull request by mjgiarlo**
# Why was this change made?

- **Add H3 to the list of deployable projects**
- **Parallelize SSH checking**

# How was this change tested?

Ran the deployer and SSH checker.

### CODE REVIEW

**Comment by edsu** [comment]
Parallelizing these checks is another way to get locked out if you don't have an active ProxyJump. But I guess there's no getting around that, other than maybe a warning/prompt?

**Review by edsu — APPROVED** [review]

**Comment by mjgiarlo** [comment]
@edsu 💬 
> Parallelizing these SSH checks is another way to get locked out if you don't have an active ProxyJump.

It'll get you locked out more quickly than when it's run serially, for sure.

> But I guess there's no getting around that, other than maybe a warning/prompt?

Sure, maybe a warning or prompt would be helpful. With the change in this branch, I believe all of the functions in sdr-deploy now operate in parallel. Where/when do you think is the best time to warn/prompt? In the deployer or the SSH checker, or both?

**Comment by edsu** [comment]
You're right we currently have the same problem w/ sdr-deploy. Maybe we could merge this as is, and add another issue for warning/guarding against accidental blocks?

**Comment by mjgiarlo** [comment]
@edsu 💬 
> You're right we currently have the same problem w/ sdr-deploy. Maybe we could merge this as is, and add another issue for warning/guarding against accidental blocks for operations that can trigger it?

Either's fine by me. I'm curious where/when/how often we should be warning/guarding, too. Maybe we could discuss in dev planning?

**Comment by mjgiarlo** [comment]
@edsu Added agenda topic: https://docs.google.com/document/d/1gzKgbqnlCc_GctBBpoYTvZl22mNZflsbqzyz4xXJlho/edit?tab=t.0#heading=h.sunrhbpqofaw

Thanks!

**Comment by mjgiarlo** [comment]
@edsu We discussed this in dev planning and decided to add a prompt to the commands in sdr-deploy that make SSH connections. We may also sniff for existing control master connections. Aaron's gonna take a hack at that this week. Thanks for raising this!

**Pull request merged**
