### PR TITLE
Accommodate deploying and ssh-checking of oddball envs

### PR DESCRIPTION
**Pull request by mjgiarlo**
Please hold until @lwrubel has deployed to prod this week.

## Why was this change made?

This commit is a spike to see what it might take to get sdr-deploy to deploy a couple of one-off app environments, specifically ETD UAT and sul_pub cap-dev. The status checker is also now env-aware:

```
------- RESULTS: -------
┌──────────────────────────┬─────────────┬─────────────┐
│repo                      │deploy result│status result│
├──────────────────────────┼─────────────┼─────────────┤
│sul-dlss/hydra_etd        │success      │success      │
│sul-dlss/hydra_etd (uat)  │success      │success      │
│sul-dlss/sul_pub          │success      │success      │
│sul-dlss/sul_pub (cap-dev)│success      │success      │
└──────────────────────────┴─────────────┴─────────────┘
```

## How was this change tested?

Ran ssh check, deploy, and tagger with diff codebases (all tests run against QA as other envs should not be affected)

## Which documentation and/or configurations were updated?

README

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Accompanying doc change: https://github.com/sul-dlss/DeveloperPlaybook/pull/174

**Review by ndushay — APPROVED** [review]
Looks good;  WFM if it works.

If you want it merged, you might take `[SPIKE]` out of the title.

For future:  I try to keep rubocop noise, esp. auto-gen-config, as a separate commit.  Whatevs.

**Comment by mjgiarlo** [comment]
@ndushay 💬 
> Looks good; WFM if it works.
> 
> If you want it merged, you might take `[SPIKE]` out of the title.

Buh, I actually meant to `[HOLD]` it, which I've now done.
 
> For future: I try to keep rubocop noise, esp. auto-gen-config, as a separate commit. Whatevs.

I generally do not consider generating rubocop TODOs important enough to justify its own commit. As long as commits are logical, maybe this is one of those practices where divergence isn't a smell.

**Comment by lwrubel** [comment]
I'm done deploying, taking off HOLD and merging.

**Pull request merged**
